spring:
  application:
    name: proxyService

  cloud:
    config:
      profile: dev
      label: master
       #是从配置中心读取文件
      discovery.enabled: true
      #配置中心服务id,即服务名
      discovery.serviceId: configService
      #配置客户端快速失败
      failFast: false

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://${config.host:127.0.0.1}:1111/eureka/

zuul:
  ignoredServices: '*'
  routes:
    user: teachingClass_command_path
      path: /command/**
      stripPrefix: false
      serviceId: teachingClass-commandService
    uesr: teachingClass_query_path
      serviceId: teachingClass-queryService
      path: /query/**
      stripPrefix: false